### Exercise 6: Adding, Removing, and Moving Columns

**Requirements:**
1. Add a new column called `'Total'` that sums up: `'HP'`, `'Attack'`, `'Defense'`, `'Sp. Atk'`, `'Sp. Def'`, and `'Speed'`:
   - Try doing this by adding the columns one by one.
   - Also try doing this using `.iloc` and `.sum(axis=1)`.
2. Add a new column called `'Dead/Alive'` and fill all rows with the word `'alive'`.
3. Temporarily drop the `'Dead/Alive'` column and drop row index 0 to see how `.drop()` works.
4. Rearrange the columns so the `'Total'` column sits right after the `'Name'` column.

<details>
<summary>💡 Need a hint?</summary>

- Add sum column: `df['Total'] = df.iloc[:, 4:10].sum(axis=1)`
- Add single text to all rows: `df['Dead/Alive'] = ['alive'] * len(df)`
- Drop column/row: `df.drop(columns='Dead/Alive')` or `df.drop(index=0)`
- Rearrange order: `cols = list(df.columns.values); df = df[cols[0:2] + [cols[-1]] + cols[2:-1]]`
</details>

Import TXT dataset as Dataframe

In [2]:
import pandas as pd

df = pd.read_csv('./data/pokemon_data.txt', delimiter='\t' )

df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

1. Add a new column called `'Total'` that sums up: `'HP'`, `'Attack'`, `'Defense'`, `'Sp. Atk'`, `'Sp. Def'`, and `'Speed'`:
   - Try doing this by adding the columns one by one.

In [3]:
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

1. Add a new column called `'Total'` that sums up: `'HP'`, `'Attack'`, `'Defense'`, `'Sp. Atk'`, `'Sp. Def'`, and `'Speed'`:
   - Also try doing this using `.iloc` and `.sum(axis=1)`.

In [4]:
df['Tot'] = df.iloc[:,4:10] .sum(axis=1)

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Tot
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

2. Add a new column called `'Dead/Alive'` and fill all rows with the word `'alive'`.

In [5]:
df['Dead/Alive'] = ['Alive'] * len(df)

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Tot,Dead/Alive
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318,Alive
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405,Alive
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525,Alive
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625,Alive
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,600,Alive
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,700,Alive
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,600,Alive
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,680,Alive
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600,Alive

3. Temporarily drop the `'Dead/Alive'` column and drop row index 0 to see how `.drop()` works.

In [6]:
df.drop(columns='Dead/Alive')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Tot
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

In [7]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Tot,Dead/Alive
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318,Alive
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405,Alive
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525,Alive
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625,Alive
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,600,Alive
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,700,Alive
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,600,Alive
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,680,Alive
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600,Alive

In [8]:
df.drop(columns='Dead/Alive', inplace=True)

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Tot
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

4. Rearrange the columns so the `'Total'` column sits right after the `'Name'` column.

In [13]:
df[['#','Name','Total','Type 1','Type 2','HP','Attack','Defense','Sp. Atk','Sp. Def','Speed','Generation','Legendary','Tot']]

,#,Name,Total,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Tot
0,1,Bulbasaur,318,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,405,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,525,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,625,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,309,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,600,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,700,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,600,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,680,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,600,Fire,Water,80,110,120,130,90,70,6,True,600