### Exercise 8: Filtering Data & Resetting the Index

**Requirements:**
1. Find all Pokémon that are **BOTH** `'Grass'` Type 1 **AND** `'Poison'` Type 2.
2. Find all Pokémon that are **EITHER** `'Grass'` Type 1 **OR** `'Poison'` Type 2.
3. Find all Pokémon that are **NOT** Grass and **NOT** Poison.
4. Take that filtered result (not Grass, not Poison), reset the index back to 0, 1, 2..., and remove the old index column.

<details>
<summary>💡 Need a hint?</summary>

- AND filter: `df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]`
- OR filter: `df.loc[(df['Type 1'] == 'Grass') | (df['Type 2'] == 'Poison')]`
- NOT filter: `df.loc[~((df['Type 1'] == 'Grass') | (df['Type 2'] == 'Poison'))]`
- Reset index cleanly: `.reset_index(drop=True)`
</details>

----

Import TXT dataset as Dataframe

In [10]:
import pandas as pd

df = pd.read_csv('./data/pokemon_data.txt', delimiter='\t')

df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

1. Find all Pokémon that are **BOTH** `'Grass'` Type 1 **AND** `'Poison'` Type 2.

In [11]:
df.loc[ (df['Type 1']=='Grass') & (df['Type 2']=='Poison') ]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

2. Find all Pokémon that are **EITHER** `'Grass'` Type 1 **OR** `'Poison'` Type 2.

In [12]:
df.loc[ (df['Type 1']=='Grass') | (df['Type 2']=='Poison') ]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

3. Find all Pokémon that are **NOT** Grass and **NOT** Poison.

In [13]:
df.loc[ ~((df['Type 1']=='Grass') & (df['Type 2']=='Poison')) ]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

4. Take that filtered result (not Grass, not Poison), reset the index back to 0, 1, 2..., and remove the old index column.

In [14]:
df.loc[ ~((df['Type 1']=='Grass') & (df['Type 2']=='Poison')) ] .reset_index(drop=True)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
1,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
2,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
3,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
4,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
780,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
781,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
782,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
783,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
784,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True